#!/bin/bash

# flush memory with use-once page cache reads

# lru_lock coverage
# 1781926	____pagevec_lru_add
#  736056	shrink_inactive_list

source hw_vars

for i in `seq 1 $nr_cpu`
do
	create_sparse_file $SHM_FILE-$i $((10 * mem / nr_cpu))
	$USEMEM -f $SHM_FILE-$i --readonly --random $((10 * mem / nr_cpu)) &
done

wait

rm `seq -f $SHM_FILE-%g 1 $nr_cpu`
